In [8]:
import numpy as np

In [ ]:
def solve(A, b):
    x = np.zeros_like(b)
    for col in range(1, A.shape[1]):
        for row in range(col, A.shape[0]):
            zeroiator = (- A[row, col-1]/A[col-1, col-1])
            A[row] = A[row] + A[col-1] * zeroiator
            b[row] = b[row] + b[col-1] * zeroiator
        print(A)
        print(b)
    # print(A)
    # print(b)
    # x[-1] = b[-1] / A[-1, -1]
    # x[-2] = (b[-2] - A[-2, -1] * x[-1]) / A[-2, -2]
    # x[-3] = (b[-3] - A[-3, -1] * x[-1] - A[-3, -2] * x[-2]) / A[-3, -3]
    for col in range(A.shape[1]-1, -1, -1):
        result = 0
        for row in range(A.shape[0]-1, col, -1):
            result += A[col, row] * x[row]
        x[col] = (b[col] - result)/A[col, col]


    return x
A = np.array([
    [6.59, 1.28, 0.79, 1.195, -0.21],
    [0.92, 3.83, 1.3, -1.63, 1.02],
    [1.15, -2.46, 5.77, 2.1, 1.483],
    [1.285, 0.16, 2.1, 5.77, -18],
    [0.69, -1.68, -1.217, 9, -6]
])
# A = np.array([[  6.59    ,   1.28    ,   0.79    ,   1.195   ,  -0.21    ],
#         [  1.0925  ,   3.41    ,   0.99575 ,   0.62    ,  -0.48    ],
#         [  2.024   ,   0.268   ,   6.5666  ,   2.596   ,   1.099   ],
#         [ -0.2882  ,   3.9904  ,   4.87476 , -14.75    ,  -4.32    ],
#         [  0.57472 ,  -0.08384 ,   0.732904,   3.1     ,  -7.728   ]])
A_start = A.copy()
b = np.array([
    [2.1],
    [0.36],
    [3.89],
    [11.04],
    [-0.27]
])
b_start = b.copy()
x = solve(A, b)
print()
print()
print(x)
r = abs(b_start - A_start@x)
print()
print(r)
print()
print()
print(A_start@x)
print()
print(b_start)


[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.1977997    0.86478263   0.42189112  -0.44518589]
 [  0.          -0.12512898   6.32396571   2.22897724   1.16349772]
 [  0.           4.04637815   4.90930901 -14.69773915  -4.32918392]
 [  0.          -0.19546998   0.66400737   2.99578294  -7.70968571]]
[[ 2.1       ]
 [ 0.01185888]
 [ 3.24502276]
 [11.13183915]
 [-0.45314294]]
[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.1977997    0.86478263   0.42189112  -0.44518589]
 [  0.           0.           6.3578044    2.24548572   1.14607773]
 [  0.           0.           3.81504488 -15.23158466  -3.76586206]
 [  0.           0.           0.71686842   3.02157163  -7.73689832]]
[[ 2.1       ]
 [ 0.01185888]
 [ 3.2454868 ]
 [11.11683336]
 [-0.45241805]]
[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.1977997    0.86478263   0.42189112  -0.44518589]
 [  0.           0.           