In [8]:
import numpy as np

In [42]:
def solve(A, b):
    x = np.zeros_like(b)
    for col in range(1, A.shape[1]):
        for row in range(col, A.shape[0]):
            zeroiator = (- A[row, col-1]/A[col-1, col-1])
            A[row] = A[row] + A[col-1] * zeroiator
            b[row] = b[row] + b[col-1] * zeroiator
        print(A)
        print(b)
    # print(A)
    # print(b)
    # x[-1] = b[-1] / A[-1, -1]
    # x[-2] = (b[-2] - A[-2, -1] * x[-1]) / A[-2, -2]
    # x[-3] = (b[-3] - A[-3, -1] * x[-1] - A[-3, -2] * x[-2]) / A[-3, -3]
    for col in range(A.shape[1]-1, -1, -1):
        result = 0
        for row in range(A.shape[0]-1, col, -1):
            result += A[col, row] * x[row]
        x[col] = (b[col] - result)/A[col, col]


    return x
A = np.array([
    [6.59, 1.28, 0.79, 1.195, -0.21],
    [0.92, 3.83, 1.3, -1.63, 1.02],
    [1.15, -2.46, 5.77, 2.1, 1.483],
    [1.285, 0.16, 2.1, 5.77, -18],
    [0.69, -1.68, -1.217, 9, -6]
])
A_start = A.copy()
b = np.array([
    [2.1],
    [0.36],
    [3.89],
    [11.04],
    [-0.27]
])
b_start = b.copy()
x = solve(A, b)
print()
print()
print(x)
r = abs(b_start - A_start@x)
print()
print(r)
# print()
# print()
# print(A_start@x)
# print()
# print(b_start)


[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.65130501   1.18971168  -1.79682853   1.04931715]
 [  0.          -2.68336874   5.63213961   1.89146434   1.51964643]
 [  0.          -0.08959029   1.94595599   5.53698407 -17.95905159]
 [  0.          -1.81402124  -1.29971624   8.8748786   -5.97801214]]
[[ 2.1       ]
 [ 0.06682853]
 [ 3.52353566]
 [10.63051593]
 [-0.4898786 ]]
[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.65130501   1.18971168  -1.79682853   1.04931715]
 [  0.           0.           6.50646677   0.5709629    2.2907967 ]
 [  0.           0.           1.97514737   5.49289616 -17.93330501]
 [  0.           0.          -0.70865023   7.98218815  -5.45669617]]
[[ 2.1       ]
 [ 0.06682853]
 [ 3.5726484 ]
 [10.63215567]
 [-0.45667722]]
[[  6.59         1.28         0.79         1.195       -0.21      ]
 [  0.           3.65130501   1.18971168  -1.79682853   1.04931715]
 [  0.           0.           