In [8]:
import numpy as np

In [9]:
def if_diag_pan(matrix, print_do=False):
    flag = True
    for row in range(matrix.shape[0]):
        flag &= abs(matrix[row, row]) >= sum(abs(matrix[row])) - abs(matrix[row, row])
    if print_do:
        print("Diag_Pan" if flag else "Not_Diag_Pan")
    return flag

In [10]:
A = np.array([
    [6.59, 1.28, 0.79, 1.195, -0.21],
    [0.92, 3.83, 1.3, -1.63, 1.02],
    [1.15, -2.46, 5.77, 2.1, 1.483],
    [1.285, 0.16, 2.1, 5.77, -18],
    [0.69, -1.68, -1.217, 9, -6]
])
A_start = A
b = np.array([
    [2.1],
    [0.36],
    [3.89],
    [11.04],
    [-0.27]
])
b_start = b
A[1] += A[4]*1/4
b[1] += b[4]*1/4
# [ 0.25088613  0.79731537 -2.27511493  0.41375988]
A[2] += A[1]*0.8
b[2] += b[1]*0.8
# A[2] += A[1]*0.9565445
A[3] += A[4]*-2.28
b[3] += b[4]*-2.28
# A[3] += A[4]*-3.18926847
A[4] += A[3]*0.4
b[4] += b[3]*0.4
# A[4] += A[3]*0.20868201
if_diag_pan(A, print_do=True)
A, b


Diag_Pan


(array([[  6.59    ,   1.28    ,   0.79    ,   1.195   ,  -0.21    ],
        [  1.0925  ,   3.41    ,   0.99575 ,   0.62    ,  -0.48    ],
        [  2.024   ,   0.268   ,   6.5666  ,   2.596   ,   1.099   ],
        [ -0.2882  ,   3.9904  ,   4.87476 , -14.75    ,  -4.32    ],
        [  0.57472 ,  -0.08384 ,   0.732904,   3.1     ,  -7.728   ]]),
 array([[ 2.1    ],
        [ 0.2925 ],
        [ 4.124  ],
        [11.6556 ],
        [ 4.39224]]))

In [11]:
C = np.zeros_like(A)
d = np.zeros_like(b)
for row in range(A.shape[0]):
    C[row] = (-A[row])/A[row, row]
    C[row, row] = 0
    d[row] = b[row]/A[row, row]
print(C)
print(d)
print()
print()
for row in range(C.shape[0]):
    print(sum(abs(C[row])), sum(abs(C[:, row])))


[[ 0.         -0.19423369 -0.1198786  -0.18133536  0.03186646]
 [-0.32038123  0.         -0.2920088  -0.18181818  0.14076246]
 [-0.30822648 -0.0408126   0.         -0.39533396 -0.16736211]
 [-0.01953898  0.27053559  0.3304922   0.         -0.29288136]
 [ 0.07436853 -0.01084886  0.09483747  0.40113872  0.        ]]
[[ 0.31866464]
 [ 0.08577713]
 [ 0.62802668]
 [-0.79021017]
 [-0.56835404]]


0.5273141122913505 0.7225152241997499
0.9349706744868035 0.5164307389913462
0.9117351445192339 0.837217079109244
0.9134481355932205 1.1596262175565482
0.5811935817805383 0.6328723888142584


In [12]:
def Iteration_simple_method(C, d, epsilon=1e-4):
    xk = np.zeros(b.shape)
    xk1 = C@xk + d

    count = 0

    r = abs(b_start - A_start@xk1)
    print(f"[{count}] r: \n {r} \n")
    print(f"[{count}] x: \n {xk1} \n\n")
    
    q = np.zeros(b.shape)
    for row in range(C.shape[0]):
        q = min(sum(abs(C[row])), sum(abs(C[:, row])))

    while q/(1-q) * np.max(abs(xk1 - xk)) >= epsilon:
        xk = xk1
        xk1 = C@xk + d
    
        count += 1
    
        r = abs(b_start - A_start@xk1)
        print(f"[{count}] r: \n {r} \n")
        print(f"[{count}] x: \n {xk1} \n\n")

    return xk1


x = Iteration_simple_method(C, d)

print(A_start@x)
print(b_start)

[0] r: 
 [[0.21901101]
 [0.75637832]
 [2.00804118]
 [5.76721468]
 [1.81341687]] 

[0] x: 
 [[ 0.31866464]
 [ 0.08577713]
 [ 0.62802668]
 [-0.79021017]
 [-0.56835404]] 


[1] r: 
 [[0.47417961]
 [0.69585762]
 [0.76496323]
 [1.60969837]
 [1.47390867]] 

[1] x: 
 [[ 0.35189848]
 [-0.1360347 ]
 [ 0.93382286]
 [-0.39921256]
 [-0.80300943]] 


[2] r: 
 [[0.26287021]
 [0.21849338]
 [0.29258683]
 [2.18535873]
 [0.22868634]] 

[2] x: 
 [[ 0.27994407]
 [-0.34009852]
 [ 0.81732981]
 [-0.29008047]
 [-0.61228626]] 


[3] r: 
 [[0.13645018]
 [0.10685171]
 [0.25419385]
 [0.10085488]
 [0.47439844]] 

[3] x: 
 [[ 0.31983332]
 [-0.27602421]
 [ 0.77277299]
 [-0.43824039]
 [-0.58269434]] 


[4] r: 
 [[0.07540986]
 [0.08639293]
 [0.03490878]
 [0.57296527]
 [0.01644702]] 

[4] x: 
 [[ 0.34053896]
 [-0.2446894 ]
 [ 0.81148311]
 [-0.445078  ]
 [-0.6440813 ]] 


[5] r: 
 [[0.01774368]
 [0.01585437]
 [0.07323021]
 [0.08107878]
 [0.11986356]] 

[5] x: 
 [[ 0.32909589]
 [-0.27002457]
 [ 0.81679922]
 [-0.4062329 ]

In [13]:
# from time import time
# A = np.array([
#     [6.59, 1.28, 0.79, 1.195, -0.21],
#     [0.92, 3.83, 1.3, -1.63, 1.02],
#     [1.15, -2.46, 5.77, 2.1, 1.483],
#     [1.285, 0.16, 2.1, 5.77, -18],
#     [0.69, -1.68, -1.217, 9, -6]
# ])
# unit = [0, 0, 0, 0]
# member = [0, 0, 0, 0]
# start_time = time()
# while not if_diag_pan(A):
#     A = np.array([
#         [6.59, 1.28, 0.79, 1.195, -0.21],
#         [0.92, 3.83, 1.3, -1.63, 1.02],
#         [1.15, -2.46, 5.77, 2.1, 1.483],
#         [1.285, 0.16, 2.1, 5.77, -18],
#         [0.69, -1.68, -1.217, 9, -6]
#     ])
#     unit = np.random.uniform(-4, 4, 4)
#     member = np.random.randint(0, A.shape[0], size=4)
#     for member_index in range(member.shape[0]):
#         while member[member_index] == member_index+1:
#             member[member_index] = np.random.randint(0, A.shape[0])
#     # member = [4, 1, 4, 3]
#     A[1] += A[member[0]]*unit[0]
#     A[2] += A[member[1]]*unit[1]
#     A[3] += A[member[2]]*unit[2]
#     A[4] += A[member[3]]*unit[3]
#     if time() - start_time > 480:
#         break
 
# print(member)
# print(unit)
# print(if_diag_pan(A))
